/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EPLAYHAVEN_AUTODEFS_H
#define S3EPLAYHAVEN_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_PLAYHAVEN_NAME "s3ePlayhaven"
#define S3E_EXT_PLAYHAVEN_HASH 0x6e72b638

#endif /* !S3EPLAYHAVEN_AUTODEFS_H */
